1. improved bakp to take into account time of day, already running process, logfile, device state
2. improved bright to take into account lvl first before time of day

3. improved mmap by including mapgen values

4. improved cron to ditch async updates

5. other incremental updates

diff --git a/.local/bin/bakp b/.local/bin/bakp
--- a/.local/bin/bakp
+++ b/.local/bin/bakp
@@ -1,27 +1,73 @@
 #!/bin/sh
 #bakp
 # mount removable backup media, backup to it and unmount it
-# if LABEL=backup drive not mounted, mount it
 
+time=$(/usr/bin/date +%H)
+logfile="$HOME/.local/share/bakp.log"
 loaded=$(/usr/bin/findmnt -S LABEL=backup)
 #mountpoint=$(/usr/bin/lsblk -l -o +LABEL | /usr/bin/grep backup | /usr/bin/awk '{print $1}') # too much awk!
 mountpoint=$(/usr/bin/lsblk -l -o +LABEL | /usr/bin/grep backup | /usr/bin/cut -c -4)
 
-if [ -z "$loaded" ]; then
-	/usr/bin/pmount /dev/"$mountpoint" backup && /usr/bin/notify-send "backup started"
+# if no drive found, abort
+# if LABEL=backup drive found, but not mounted, then mount it
+# if backup for today already done, abort, if not continue
+# backup often takes hours, stop script from re-running if another instance of rsync is present
+
+if [ -n "$mountpoint" ] && [ -z "$loaded" ] && [ "$time" -ge 11 ] && [ "$time" -lt 19 ]; then
+    if /usr/bin/grep -Eq "$(/usr/bin/date +%F).completed" "$logfile"; then
+        /usr/bin/notify-send -u critical "backup aborted" "backup for today done"
+        /usr/bin/echo "backup for Sunday $(/usr/bin/date +%F) aborted at $(/usr/bin/date +%H%M), already done" >> "$logfile"
+        exit 1
+    elif [ -n "$(/usr/bin/pgrep rsync)" ]; then
+        /usr/bin/notify-send -u critical "backup in progress" "aborting..."
+        exit 1
+    else
+        /usr/bin/pmount /dev/"$mountpoint" backup
+        /usr/bin/notify-send -u critical "backup started" "no backup for today found"
+        /usr/bin/echo "backup for Sunday $(/usr/bin/date +%F) started at $(/usr/bin/date +%H%M)hrs" >> "$logfile"
+    fi
+else
+    /usr/bin/notify-send -u critical "no device found" "backup aborted"
+    /usr/bin/echo "backup for Sunday $(/usr/bin/date +%F) aborted at $(/usr/bin/date +%H%M)hrs, no device found" >> "$logfile"
+    exit 1
 fi
 
-# start syncing to backup and back
+# start syncing to backup and back, logging each individual rsync errors to logfile
 # /usr/bin/rsync --verbose --itemize-changes --archive --checksum -hh --partial --progress --info=stats1 --recursive --modify-window=1 ~/.bak/crypt-bak/ -t /media/backup/ts-bak/bak/crypt-bak && /usr/bin/rsync --verbose --itemize-changes --archive --checksum -hh --partial --progress --info=stats1 --recursive --modify-window=1 /media/backup/ts-bak/bak/crypt-bak/ -t ~/.bak/crypt-bak; # keeping line for old arguments
-/usr/bin/rsync --archive --checksum --partial --recursive ~/.bak/crypt-bak/ \
+/usr/bin/notify-send -u critical "secret backup started"
+
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/.bak/crypt-bak/ \
  -t /media/backup/ts-bak/bak/crypt-bak \
+ 2>> "$logfile" \
     && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/bak/crypt-bak/ \
- -t ~/.bak/crypt-bak;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/.bak/etc-bak/ \
+ -t ~/.bak/crypt-bak \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "secret backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "secret backup done"
+fi
+
+/usr/bin/notify-send -u critical "etc backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/.bak/etc-bak/ \
  -t /media/backup/ts-bak/bak/etc-bak \
+ 2>> "$logfile" \
     && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/bak/etc-bak/ \
- -t ~/.bak/etc-bak;
-/usr/bin/rsync --archive --checksum --partial --recursive \
+ -t ~/.bak/etc-bak \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "etc backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "etc backup done"
+fi
+
+/usr/bin/notify-send -u critical "config backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive \
+    --exclude '*.o' \
+    --exclude 'dmenu' \
+    --exclude 'dwm' \
+    --exclude 'dwmblocks' \
+    --exclude 'sent' \
+    --exclude 'st' \
+    --exclude 'stest' \
     ~/.config/aerc \
     ~/.config/alacritty \
     ~/.config/bash \
@@ -55,46 +101,129 @@ fi
     ~/.config/user-dirs.dirs \
     ~/.config/user-dirs.locale \
  -t /media/backup/ts-bak/bak/conf-bak \
+ 2>> "$logfile" \
     && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/bak/conf-bak/ \
- -t ~/.config;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/.local/bin/ \
+ -t ~/.config \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "config backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "config backup done"
+fi
+
+/usr/bin/notify-send -u critical "local/bin backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/.local/bin/ \
  -t /media/backup/ts-bak/bak/local-bak/bin \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/bak/local-bak/bin/ \
- -t ~/.local/bin;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/.local/share/bookmarks \
+ -t ~/.local/bin \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "local/bin backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "local/bin backup done"
+fi
+
+/usr/bin/notify-send -u critical "local/share backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive \
+    ~/.local/share/bookmarks \
+    ~/.local/share/emoji.txt \
  -t /media/backup/ts-bak/bak/local-bak/share \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/bak/local-bak/share/ \
- -t ~/.local/share;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/.arx/ \
+ -t ~/.local/share \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "local/share backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "local/share backup done"
+fi
+
+/usr/bin/notify-send -u critical "archive backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/.arx/ \
  -t /media/backup/ts-bak/arx \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/arx/ \
- -t ~/.arx;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/dox/ \
+ -t ~/.arx \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "archive backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "archive backup done"
+fi
+
+/usr/bin/notify-send -u critical "dox backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/dox/ \
  -t /media/backup/ts-bak/dox \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/dox/ \
- -t ~/dox;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/notx/ \
+ -t ~/dox \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "dox backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "dox backup done"
+fi
+
+/usr/bin/notify-send -u critical "notx backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/notx/ \
  -t /media/backup/ts-bak/notx \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/notx/ \
- -t ~/notx;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/nvl/ \
+ -t ~/notx \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "notx backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "notx backup done"
+fi
+
+/usr/bin/notify-send -u critical "nvl backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/nvl/ \
  -t /media/backup/ts-bak/nvl \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/nvl/ \
- -t ~/nvl;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/rsc/ \
+ -t ~/nvl \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "nvl backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "nvl backup done"
+fi
+
+/usr/bin/notify-send -u critical "rsc backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/rsc/ \
  -t /media/backup/ts-bak/rsc \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/rsc/ \
- -t ~/rsc;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/sty/ \
+ -t ~/rsc \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "rsc backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "rsc backup done"
+fi
+
+/usr/bin/notify-send -u critical "sty backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/sty/ \
  -t /media/backup/ts-bak/sty \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/sty/ \
- -t ~/sty;
-/usr/bin/rsync --archive --checksum --partial --recursive ~/wfu/ \
+ -t ~/sty \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "sty backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "sty backup done"
+fi
+
+/usr/bin/notify-send -u critical "wfu backup started"
+if ! /usr/bin/rsync --archive --checksum --partial --recursive ~/wfu/ \
  -t /media/backup/ts-bak/wfu \
+ 2>> "$logfile" \
  && /usr/bin/rsync --archive --checksum --partial --recursive /media/backup/ts-bak/wfu/ \
- -t ~/wfu;
+ -t ~/wfu \
+ 2>> "$logfile"; then
+    /usr/bin/notify-send -u critical "wfu backup failed" "check error log"
+else
+    /usr/bin/notify-send -u low "wfu backup done"
+fi
+
 /usr/bin/notify-send "backup complete"
+/usr/bin/echo "backup for Sunday $(/usr/bin/date +%F) completed at $(/usr/bin/date +%H%M)" >> "$logfile"
 
 # unmount backup drive
 /usr/bin/pumount /dev/"$mountpoint"
 /usr/bin/notify-send "backup drive unmounted"
+
