in preparation of guix packages, updated scripts to point to named binaries in path, not just those in /usr/bin or /usr/local/bin.

diff --git a/.local/bin/ccc b/.local/bin/ccc
--- a/.local/bin/ccc
+++ b/.local/bin/ccc
@@ -7,95 +7,95 @@
 # check if file is empty or if URL link is valid, before continuing
 # if URL only named 'readme', change output to name of parent directory
 
-# if [ -z "$(/usr/bin/xclip -o)" ]; then
-#     if [ -z "$(/usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url')" ]; then
-#         /usr/bin/printf "%s\n" "Error, neither URL link nor URL file found"
+# if [ -z "$(xclip -o)" ]; then
+#     if [ -z "$(find . -maxdepth 1 -mindepth 1 -type f -name '*url')" ]; then
+#         printf "%s\n" "Error, neither URL link nor URL file found"
 #         exit 1
-#     elif /usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url' | /usr/bin/xargs /usr/bin/grep -Eiq 'http[s]://[^ ]+'; then
-#             /usr/bin/notify-send -u low "readme URL file found"
-#             projdir="$(/usr/bin/pwd | /usr/bin/sed 's@.*/@@')"
-#             exturl="$(/usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url' | \
-#                 /usr/bin/xargs /usr/bin/grep -Eio 'http[s]://[^ ]+' | \
-#                 /usr/bin/sed 's@.*\.@@')"
+#     elif find . -maxdepth 1 -mindepth 1 -type f -name '*url' | xargs grep -Eiq 'http[s]://[^ ]+'; then
+#             notify-send -u low "readme URL file found"
+#             projdir="$(pwd | sed 's@.*/@@')"
+#             exturl="$(find . -maxdepth 1 -mindepth 1 -type f -name '*url' | \
+#                 xargs grep -Eio 'http[s]://[^ ]+' | \
+#                 sed 's@.*\.@@')"
 #             if [ -z "$exturl" ]; then
-#                 /usr/bin/curl -O "$(/usr/bin/cat "$(/usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
+#                 curl -O "$(cat "$(find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
 #             else
-#                 /usr/bin/curl -o "$projdir.$exturl" "$(/usr/bin/cat "$(/usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
+#                 curl -o "$projdir.$exturl" "$(cat "$(find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
 #             fi
 #     else
-#         /usr/bin/printf "%s\n" "Error, no valid URL found in file"
+#         printf "%s\n" "Error, no valid URL found in file"
 #         exit 1
 #     fi
-# elif /usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | /usr/bin/grep -Eiq 'http[s]://[^ ]+'; then
-#         /usr/bin/notify-send -u low "valid URL link found"
-#         projdir="$(/usr/bin/pwd | /usr/bin/sed 's@.*/@@')"
-#         projurl="$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | \
-#             /usr/bin/xargs /usr/bin/basename | /usr/bin/sed 's@\..*$@@')"
-#         exturl="$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | /usr/bin/sed 's@.*\.@@')"
+# elif printf "%s" "$(xclip -o)" | grep -Eiq 'http[s]://[^ ]+'; then
+#         notify-send -u low "valid URL link found"
+#         projdir="$(pwd | sed 's@.*/@@')"
+#         projurl="$(printf "%s" "$(xclip -o)" | \
+#             xargs basename | sed 's@\..*$@@')"
+#         exturl="$(printf "%s" "$(xclip -o)" | sed 's@.*\.@@')"
 #         if [ "$projdir" = "$projurl" ]; then
 #             if [ -z "$exturl" ]; then
-#                 /usr/bin/curl -O "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"    
+#                 curl -O "$(printf "%s" "$(xclip -o)")"    
 #             else
-#                 /usr/bin/curl -o "$projdir.$exturl" "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"
+#                 curl -o "$projdir.$exturl" "$(printf "%s" "$(xclip -o)")"
 #             fi
 #         elif
-#             /usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | /usr/bin/grep -q "$projdir"; then
+#             printf "%s" "$(xclip -o)" | grep -q "$projdir"; then
 #             if [ -z "$exturl" ]; then
-#                 /usr/bin/curl -O "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"    
+#                 curl -O "$(printf "%s" "$(xclip -o)")"    
 #             else
-#                 /usr/bin/curl -o "$projdir.$exturl" "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"
+#                 curl -o "$projdir.$exturl" "$(printf "%s" "$(xclip -o)")"
 #             fi
 #         else
-#             /usr/bin/printf "%s\n" "Error, URL and dirname donot match."
+#             printf "%s\n" "Error, URL and dirname donot match."
 #             exit 1
 #         fi
 # else
-#     /usr/bin/printf "%s\n" "Error, not a valid URL"
+#     printf "%s\n" "Error, not a valid URL"
 #     exit 1
 # fi
 
 # instead of starting the if-else statement with checking clipboard for URL, start with checking file for URL
 
-if ! /usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url' | /usr/bin/xargs /usr/bin/grep -Eiq 'http[s]://[^ ]+'; then
-    if [ -z "$(/usr/bin/xclip -o)" ]; then
-        /usr/bin/printf "%s\n" "Error, neither URL link nor URL file found"
+if ! find . -maxdepth 1 -mindepth 1 -type f -name '*url' | xargs grep -Eiq 'http[s]://[^ ]+'; then
+    if [ -z "$(xclip -o)" ]; then
+        printf "%s\n" "Error, neither URL link nor URL file found"
         exit 1
-    elif /usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | /usr/bin/grep -Eiq 'http[s]://[^ ]+'; then
-        /usr/bin/notify-send -u low "valid URL link found"
-        projdir="$(/usr/bin/pwd | /usr/bin/sed 's@.*/@@')"
-        projurl="$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | \
-            /usr/bin/xargs /usr/bin/basename | /usr/bin/sed 's@\..*$@@')"
-        exturl="$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | /usr/bin/sed 's@.*\.@@')"
+    elif printf "%s" "$(xclip -o)" | grep -Eiq 'http[s]://[^ ]+'; then
+        notify-send -u low "valid URL link found"
+        projdir="$(pwd | sed 's@.*/@@')"
+        projurl="$(printf "%s" "$(xclip -o)" | \
+            xargs basename | sed 's@\..*$@@')"
+        exturl="$(printf "%s" "$(xclip -o)" | sed 's@.*\.@@')"
         if [ "$projdir" = "$projurl" ]; then
             if [ -z "$exturl" ]; then
-                /usr/bin/curl -O "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"    
+                curl -O "$(printf "%s" "$(xclip -o)")"    
             else
-                /usr/bin/curl -o "$projdir.$exturl" "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"
+                curl -o "$projdir.$exturl" "$(printf "%s" "$(xclip -o)")"
             fi
         elif
-            /usr/bin/printf "%s" "$(/usr/bin/xclip -o)" | /usr/bin/grep -q "$projdir"; then
+            printf "%s" "$(xclip -o)" | grep -q "$projdir"; then
             if [ -z "$exturl" ]; then
-                /usr/bin/curl -O "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"    
+                curl -O "$(printf "%s" "$(xclip -o)")"    
             else
-                /usr/bin/curl -o "$projdir.$exturl" "$(/usr/bin/printf "%s" "$(/usr/bin/xclip -o)")"
+                curl -o "$projdir.$exturl" "$(printf "%s" "$(xclip -o)")"
             fi
         else
-            /usr/bin/printf "%s\n" "Error, URL and dirname donot match"
+            printf "%s\n" "Error, URL and dirname donot match"
             exit 1
         fi
     else
-        /usr/bin/printf "%s\n" "Error, no valid URL found in file"
+        printf "%s\n" "Error, no valid URL found in file"
         exit 1
     fi
 else 
-    /usr/bin/notify-send -u low "URL file found"
-    projdir="$(/usr/bin/pwd | /usr/bin/sed 's@.*/@@')"
-    exturl="$(/usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url' | \
-        /usr/bin/xargs /usr/bin/grep -Eio 'http[s]://[^ ]+' | \
-        /usr/bin/sed 's@.*\.@@')"
+    notify-send -u low "URL file found"
+    projdir="$(pwd | sed 's@.*/@@')"
+    exturl="$(find . -maxdepth 1 -mindepth 1 -type f -name '*url' | \
+        xargs grep -Eio 'http[s]://[^ ]+' | \
+        sed 's@.*\.@@')"
     if [ -z "$exturl" ]; then
-        /usr/bin/curl -O "$(/usr/bin/cat "$(/usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
+        curl -O "$(cat "$(find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
     else
-        /usr/bin/curl -o "$projdir.$exturl" "$(/usr/bin/cat "$(/usr/bin/find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
+        curl -o "$projdir.$exturl" "$(cat "$(find . -maxdepth 1 -mindepth 1 -type f -name '*url')")"
     fi
 fi
diff --git a/.local/bin/frmt b/.local/bin/frmt
--- a/.local/bin/frmt
+++ b/.local/bin/frmt
@@ -1,14 +1,14 @@
 #!/bin/sh
 #frmt
 # format partitions
-# renamed from fmt to frmt to resolve naming conflict with fmt package in /usr/bin/
+# renamed from fmt to frmt to resolve naming conflict with fmt package in 
 
 # check whether dmenu is present, if not check for fzf, else exit
 if ! command -v dmenu > /dev/null 2>&1; then
 	if command -v fzf > /dev/null 2>&1; then
 	chooser="fzf"
 	else
-		/usr/bin/notify-send "Error" "Install dmenu or fzf to proceed"
+		notify-send "Error" "Install dmenu or fzf to proceed"
 		exit 1
 	fi
 else
@@ -18,56 +18,56 @@ fi
 # choose partition to format, abort if none selected
 # added additional grep to prevent accidental erasures
 if [ "$chooser" = "dmenu" ]; then
-	part="$(/usr/bin/lsblk -anlp -o +LABEL | \
-		/usr/bin/grep -vE "nvme|backup" | \
-		/usr/bin/grep part | \
-		/usr/bin/cut -d ' ' -f 1 | \
+	part="$(lsblk -anlp -o +LABEL | \
+		grep -vE "nvme|backup" | \
+		grep part | \
+		cut -d ' ' -f 1 | \
 		dmenu -p "select partition to format: ")"
 else
-	part="$(/usr/bin/lsblk -anlp -o +LABEL | \
-		/usr/bin/grep -vE "nvme|backup" | \
-		/usr/bin/grep part | \
-		/usr/bin/cut -d ' ' -f 1 | \
+	part="$(lsblk -anlp -o +LABEL | \
+		grep -vE "nvme|backup" | \
+		grep part | \
+		cut -d ' ' -f 1 | \
 		fzf --prompt="select partition to format: ")"
 fi
 
 # abort if no partition selected
 if [ -z "$part" ] ; then
-	/usr/bin/notify-send "Stopping..." "No valid partition selected."
+	notify-send "Stopping..." "No valid partition selected."
 	exit 1
 fi
 
 # if partition is mounted, warn, then proceed accordingly
-if [ -n "$(/usr/bin/findmnt "$part")" ]; then
+if [ -n "$(findmnt "$part")" ]; then
 	if [ "$chooser" = "dmenu" ]; then
-		affirm="$(/usr/bin/printf "%b" "yes\nno" | \
+		affirm="$(printf "%b" "yes\nno" | \
 			dmenu -p "proceed to unmount and format?")"
 	else
-		affirm="$(/usr/bin/printf "%b" "yes\nno" | \
+		affirm="$(printf "%b" "yes\nno" | \
 			fzf --prompt="proceed to unmount and format?")"
 	fi
 else
 	if [ "$chooser" = "dmenu" ]; then
-		affirm="$(/usr/bin/printf "%b" "yes\nno" | \
+		affirm="$(printf "%b" "yes\nno" | \
 			dmenu -p "proceed to format?")"
 	else
-		affirm="$(/usr/bin/printf "%b" "yes\nno" | \
+		affirm="$(printf "%b" "yes\nno" | \
 			fzf --prompt="proceed to format?")"
 	fi
 fi
 
 # if choice is negative, abort
 if [ "$affirm" = "no" ]; then
-	/usr/bin/notify-send "Stopping..." "Chose to stop."
+	notify-send "Stopping..." "Chose to stop."
 	exit 1
 fi
 
 # choose filesystem type to format to
 if [ "$chooser" = "dmenu" ]; then
-	fstype="$(/usr/bin/printf "%b" "ext4\nfat32" | \
+	fstype="$(printf "%b" "ext4\nfat32" | \
 		dmenu -p "choose filesystem type to format to: ")"
 else
-	fstype="$(/usr/bin/printf "%b" "ext4\nfat32" | \
+	fstype="$(printf "%b" "ext4\nfat32" | \
 		fzf --prompt="choose filesystem type to format to: ")"
 fi
 
@@ -76,50 +76,50 @@ if [ "$chooser" = "dmenu" ]; then
 	label="$(dmenu -p "give a label to partition: " < /dev/null)"
 else
     # label="$(fzf --prompt="give a label to partition: " --print-query)" # meaningless fuzzy searching of $HOME
-	/usr/bin/printf "%s" "give a new label to partition: " && read -r label
+	printf "%s" "give a new label to partition: " && read -r label
 fi
 
 # give a final warning
 if [ "$chooser" = "dmenu" ]; then
-	choice="$(/usr/bin/printf "%b" "yes\nno" | \
+	choice="$(printf "%b" "yes\nno" | \
 		dmenu -p "all data will be erased. really want to proceed?: ")"
 else
-	choice="$(/usr/bin/printf "%b" "yes\nno" | \
+	choice="$(printf "%b" "yes\nno" | \
 		fzf --prompt="all data will be erased. really want to proceed?: ")"
 fi
 
 if [ "$choice" = "no" ]; then
-	/usr/bin/notify-send "Stopping..." "Chose to stop formatting"
+	notify-send "Stopping..." "Chose to stop formatting"
 	exit 1
 fi
 
 # proceed with format
-if [ "$affirm" = "yes" ] && [ -n "$(/usr/bin/findmnt "$part")" ]; then
+if [ "$affirm" = "yes" ] && [ -n "$(findmnt "$part")" ]; then
 	if [ -n "$label" ]; then
 		if [ "$fstype" = "ext4" ]; then
-			/usr/bin/pumount "$part"
-			if ! /usr/bin/doas /usr/bin/mkfs.ext4 "$part" -L "$label"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			pumount "$part"
+			if ! doas mkfs.ext4 "$part" -L "$label"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		else
-			/usr/bin/pumount "$part"
-			if ! /usr/bin/doas /usr/bin/mkfs.vfat -F 32 "$part" -n "$label"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			pumount "$part"
+			if ! doas mkfs.vfat -F 32 "$part" -n "$label"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		fi
 	else
 		if [ "$fstype" = "ext4" ]; then
-			/usr/bin/pumount "$part"
-			if ! /usr/bin/doas /usr/bin/mkfs.ext4 "$part"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			pumount "$part"
+			if ! doas mkfs.ext4 "$part"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		else
-			/usr/bin/pumount "$part"
-			if ! /usr/bin/doas /usr/bin/mkfs.vfat -F 32 "$part"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			pumount "$part"
+			if ! doas mkfs.vfat -F 32 "$part"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		fi
@@ -127,25 +127,25 @@ if [ "$affirm" = "yes" ] && [ -n "$(/usr/bin/findmnt "$part")" ]; then
 else
 	if [ -n "$label" ]; then
 		if [ "$fstype" = "ext4" ]; then
-			if ! /usr/bin/doas /usr/bin/mkfs.ext4 "$part" -L "$label"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			if ! doas mkfs.ext4 "$part" -L "$label"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		else
-			if ! /usr/bin/doas /usr/bin/mkfs.vfat -F 32 "$part" -n "$label"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			if ! doas mkfs.vfat -F 32 "$part" -n "$label"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		fi
 	else
 		if [ "$fstype" = "ext4" ]; then
-			if ! /usr/bin/doas /usr/bin/mkfs.ext4 "$part"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			if ! doas mkfs.ext4 "$part"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		else
-			if ! /usr/bin/doas /usr/bin/mkfs.vfat -F 32 "$part"; then
-				/usr/bin/printf "%s\n" "Aborted"
+			if ! doas mkfs.vfat -F 32 "$part"; then
+				printf "%s\n" "Aborted"
 				exit 1
 			fi
 		fi
